# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen
image: alpine

before_script:
- apk update
- apk add doxygen
- apk add ttf-freefont graphviz

test:
  script:
  - doxygen Doxyfile
  except:
  - master

pages:
  script:
  - doxygen Doxyfile
  - mv KinovaHMICartesianControl/doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
